#!/bin/sh
# This script is only used for developement. It is removed by the
# distribution process.

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -classic-display \
                          -use-ocamlfind"}

action ()
{
    case $1 in
        default) $OCAMLBUILD bos.cmx bos_setup.cmx ;;
        tests)   $OCAMLBUILD test/tests.otarget ;;
        doc)     shift; topkg doc --dev $* ;;
        api-doc) shift; topkg doc $* ;;
        clean)   $OCAMLBUILD -clean ;;
        *)       $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
